spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create  # 완성 후 update로 변경
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    # 완성 후 여기부터 아래 끝까지 주석
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
