spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
#    username: sa
#    password: password

mybatis:
  mapper-locations: "classpath:yezy/happymybatis/mappers/*.xml"
  type-aliases-package: "com.happy.happymybatis.yezy.model"
  configuration:
    map-underscore-to-camel-case: true